services:
  web:
    container_name: web_blog
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:Artemdynamo1927@db:5432/blogdb
      - EMAIL_HOST_USER=artemruban.fhtg@gmail.com
      - EMAIL_HOST_PASSWORD=hjehcldssdnwgmvy
    depends_on:
      - db

  db:
    container_name: db_blog
    image: postgres:16
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Artemdynamo1927
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
