# Generated by Django 4.2.16 on 2024-11-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_category_title_alter_post_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
