# Generated by Django 5.0 on 2025-03-06 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_delete_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
